# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first Issue and showing your interest in @Novice-Paradigm! :bowtie:

  Feel free to join us over [Slack](https://join.slack.com/t/noviceparadigm/shared_invite/enQtNDIyMjczMzA1MzgyLWNlYmY2NjE2MGM3OTZkY2ZkNWI0ZDY2MjE0YTk2NDhjNzRmOTMyYjM0YjYwYmMxN2QxZjRiMTYzNmMyM2JlNTk) or on [Facebook](https://www.facebook.com/noviceparadigm/) for communicate with other contributors. :v:

  Please apply for [Hacktoberfest](https://hacktoberfest.digitalocean.com/). It's a fest celebrating open source where you get to win a free hacktoberfest t-shirt! :tshirt: Know more about it at the link itself.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for showing your interest in @Novice-Paradigm! :bowtie:

  Feel free to join us over [Slack](https://join.slack.com/t/noviceparadigm/shared_invite/enQtNDIyMjczMzA1MzgyLWNlYmY2NjE2MGM3OTZkY2ZkNWI0ZDY2MjE0YTk2NDhjNzRmOTMyYjM0YjYwYmMxN2QxZjRiMTYzNmMyM2JlNTk) or on [Facebook](https://www.facebook.com/noviceparadigm/) for communicate with other contributors. :v:

  Please apply for [Hacktoberfest](https://hacktoberfest.digitalocean.com/). It's a fest celebrating open source where you get to win a free hacktoberfest t-shirt! :tshirt: Know more about it at the link itself.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first Pull Request! We here at @Novice-Paradigm are proud of you!

  Feel free to join us over [Slack](https://join.slack.com/t/noviceparadigm/shared_invite/enQtNDIyMjczMzA1MzgyLWNlYmY2NjE2MGM3OTZkY2ZkNWI0ZDY2MjE0YTk2NDhjNzRmOTMyYjM0YjYwYmMxN2QxZjRiMTYzNmMyM2JlNTk) or on [Facebook](https://www.facebook.com/noviceparadigm/) for communicate with other contributors. :v:

  Please apply for [Hacktoberfest](https://hacktoberfest.digitalocean.com/). It's a fest celebrating open source where you get to win a free hacktoberfest t-shirt! :tshirt: Know more about it at the link itself.

# It is recommended to include as many gifs and emojis as possible!
